// web/service-worker.js
//
// WP-16: precaches the shell + Pyodide runtime + vendored wheels at install time (PWA-4.2), so
// the app works fully offline the moment after first install -- not merely "offline once
// you've happened to use it online once already." Never calls self.skipWaiting() on its own
// initiative -- only in response to an explicit user-triggered "reload to apply" action,
// relayed from the page via postMessage (PWA-4.4; see web/js/sw-register.js).
//
// PWA-4.3, the strongest constraint in the design doc: this file's fetch handler must never
// see, cache, or be able to leak any of the user's actual financial data. That is true *by
// construction*: imported file bytes and the computed manifest travel IndexedDB <-> page JS
// <-> Pyodide entirely in-process (see web/js/storage.js, web/py/bridge.py) and never go
// through fetch()/XHR at all, so there is nothing of that kind for this handler to ever see.
// This file's own scope is kept narrow and auditable to keep that true: it serves ONLY the
// fixed, versioned precache list below, cache-first, and passes everything else straight
// through to the network with zero runtime caching of the response -- never a catch-all
// cache-everything-the-page-asks-for proxy. tests/test_pwa_service_worker.py's
// test_online_traffic_never_carries_financial_data instruments every request made during a
// real import run and asserts none of them ever carries a byte of the fixture files or the
// computed manifest.json -- this comment states the design, that test is the actual proof.
//
// CACHE_VERSION is stamped by web/build_precache_manifest.py from a hash of every precached
// file's own content plus fina.__version__ (PWA-4.5) -- run that script whenever a precached
// file changes (WP-11's vendor bundle, any web/css|js|icons file, web/py/bridge.py) so a stale
// cache is never served and old caches actually get cleaned up on activate, rather than
// silently accumulating forever. Do not hand-edit the string below.
const CACHE_VERSION = "12b793fa2edbae29";
const CACHE_NAME = `fina-precache-${CACHE_VERSION}`;
const CACHE_NAME_PREFIX = "fina-precache-";

const MANIFEST_URL = new URL("./precache-manifest.json", self.location).href;

/**
 * Fetches `web/precache-manifest.json` (generated by `web/build_precache_manifest.py` from a
 * real directory listing of web/css, web/js, web/icons, web/py/bridge.py and
 * web/vendor/{pyodide,wheels} -- never a hand-written list that could silently drift) and
 * stores every file it names, cache-first-ready, under this version's own cache.
 */
async function _precacheAll() {
  // cache: "reload" bypasses the browser's own HTTP cache so install always fetches the real
  // current bytes, never a stale disk-cached copy of an old manifest/asset.
  const manifestResponse = await fetch(MANIFEST_URL, { cache: "reload" });
  if (!manifestResponse.ok) {
    throw new Error(
      `service-worker.js: failed to fetch ${MANIFEST_URL}: ${manifestResponse.status}`
    );
  }
  const manifestForCache = manifestResponse.clone();
  const manifest = await manifestResponse.json();
  const base = new URL("./", self.location).href;

  const cache = await caches.open(CACHE_NAME);
  await Promise.all(
    manifest.files.map(async (relPath) => {
      const url = new URL(relPath, base).href;
      const response = await fetch(url, { cache: "reload" });
      if (!response.ok) {
        throw new Error(`service-worker.js: failed to precache ${url}: ${response.status}`);
      }
      await cache.put(url, response);
    })
  );

  // The manifest itself, for completeness/self-description (nothing at runtime re-fetches it
  // after install, but caching it costs nothing and keeps the precache set fully self-
  // contained).
  await cache.put(MANIFEST_URL, manifestForCache);

  // Some navigations request the bare origin/scope root ("/") rather than "/index.html" --
  // alias it to the same cached document so both resolve identically offline.
  const indexUrl = new URL("index.html", base).href;
  const indexResponse = await cache.match(indexUrl);
  if (indexResponse) {
    await cache.put(base, indexResponse.clone());
  }
}

self.addEventListener("install", (event) => {
  // Deliberately no self.skipWaiting() here (PWA-4.4): a newly installed worker stays in the
  // standard "waiting" state behind any already-active worker/controller until the page
  // explicitly asks for it (see the "message" listener below) -- an in-progress session (e.g.
  // a chart with its tooltip open, R-10.2) is never swapped out from under the user without
  // their own say-so.
  event.waitUntil(_precacheAll());
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      // PWA-4.5: clean up every previous version's cache -- changing the precached file set
      // (a new vendor bundle, an edited shell file) changes CACHE_VERSION, which changes
      // CACHE_NAME, which means the *old* cache is simply a different key here and gets
      // deleted rather than accumulating forever.
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((key) => key.startsWith(CACHE_NAME_PREFIX) && key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      );
      await self.clients.claim();
    })()
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") {
    return; // nothing here to intercept -- let the browser handle non-GET requests normally
  }
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      const cached = await cache.match(request);
      if (cached) {
        return cached;
      }
      // Not part of the fixed, versioned precache list -- pass straight through to the
      // network, and never store the response (PWA-4.3's narrow, auditable fetch handler; see
      // this file's own header comment). There is no dynamic runtime caching of arbitrary
      // requests anywhere in this file.
      return fetch(request);
    })()
  );
});

// PWA-4.4: only ever invoked in direct response to the page's own explicit user-triggered
// message (see web/js/sw-register.js's reload-button click handler) -- never on this worker's
// own initiative.
self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
